# Generated by Django 3.1 on 2023-02-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230220_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'variations', 'verbose_name_plural': 'variations'},
        ),
    ]
